#!/bin/bash

usage () {
cat << EOF
tarman (0.9) - A package manager for installing directories.
usage: tarman install <directory> <name>
       tarman remove <name>
       tarman list

When using install, the contents of directory will be copied to / after
checking for any conflicting files.

Must be run as root.

This tool may or may not break your system.
EOF
  exit
}

error () {
  >&2 echo "tarman: $1"
  exit 1
}

rootCheck () {
  if [ "$EUID" -ne 0 ]; then
    error "Must be run as root."
  fi

  # Now that we are root, might as well create the tarman directory if it doesn't exist
  if [ ! -d /var/lib/tarman ]; then
    mkdir /var/lib/tarman # According to FHS, this is the right place to put it
  fi
}

# Prevent error when ran with no arguments
if [ $# -eq 0 ]; then
  usage
fi

if [ $1 = "install" ]; then
  rootCheck

  if [ $# -ne 3 ]; then
    error "Need directory and name."
  fi

  if [ ! -d "$2" ]; then
    error "$2: Not a directory."
  fi

  if [ -f "/var/lib/tarman/$3" ]; then
    error "Name is already used by another package."
  fi

  echo "Getting files..."
  cd "$2" # I want it to begin with ./ to make other code easier
  FILES=$(find -type f)

  echo "Checking for conflicts..."
  CONFLICTS=
  while read FILE; do # This is weird so that spaces in filenames work
    if [ -f "/$FILE" ]; then
      CONFLICTS=$CONFLICTS/$FILE$'\n'
    fi
  done <<< "$FILES"

  if [ ! -z "$CONFLICTS" ]; then
    error "Installation aborted - the following files already exist:$'\n'$CONFLICTS"
  fi

  echo "Saving package record..."
  echo -n "$FILES" > "/var/lib/tarman/$3"

  echo "Installing..."
  cp -a . /

  echo "Done!"
  exit
fi

if [ $1 = "remove" ]; then
  rootCheck

  if [ $# -ne 2 ]; then
    error "Need name."
  fi

  if [ ! -f "/var/lib/tarman/$2" ]; then
    error "Package $2 doesn't exist."
  fi

  echo "Getting files..."
  FILES=$(cat "/var/lib/tarman/$2")

  echo "Uninstalling..."
  while read FILE; do # This is weird so that spaces in filenames work
    rm "/$FILE"
  done <<< "$FILES"

  echo "Removing package record..."
  rm "/var/lib/tarman/$2"

  echo "Done!"
  exit
fi

if [ $1 = "list" ]; then
  echo "The following packages are installed:"
  # Prevent error if the first thing the user does is list
  if [ -d /var/lib/tarman ]; then
    ls /var/lib/tarman -1 --color=never
  fi
  exit
fi

# Show usage on bad action
usage
